import { tokenValidator } from './helperFunctions.js';
import { getData, setData } from './dataStore.js';
import Composite from 'composite-class';
import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

// class to pretty print prerequisites in admin portal
class PrintLogic extends Composite {
    constructor (operator) {
        super();
        this.operator = operator;
    }

    toString() {
        const children = this.children;
        let retString = "";
        for (const child in children) {
            retString += "(" + children[child] + ")";
            if (child < (children.length - 1)) {
                retString += " " + this.operator + " ";
            }
        }
        return retString;
    }
}

class childNode extends Composite {
    constructor (operand) {
        super();
        this.operand = operand;
    }

    toString() {
        return this.operand;
    }
}

async function getCourseList(token) {
// code adapted from 'adminQuizList', accessible: https://github.com/SaronMariathasan/saron-portfolio/blob/main/quizzing-server/src/quiz.ts 
    const userToken = tokenValidator(token);

    if ('error' in userToken) {
        return userToken;
    }

    const userID = userToken.tokenUserId;
    
    const data = getData();

    const user = data.user.find(user => user.userId === userID);

    let courses = [];
    // extract list of courses
    for (let code of user.courses) {
        const res = await fetch(`http://localhost:5005/info/course/${code}`);
        if (!res.ok) throw new Error("Failed to fetch course info!");
        let result = await res.json();
        courses.push(result);
    }
    return { courses };
}

function addCourse(token, courseCode, accessCode) {
    const userToken = tokenValidator(token);

    if ('error' in userToken) {
        return userToken;
    }

    const userID = userToken.tokenUserId;

    let data = getData();

    const user = data.user.find(user => user.userId == userID);
    const userIndex = data.user.findIndex(user => user.userId == userID);
    
    if (/^[A-Z]{4}\d{4}$/.test(courseCode) === false) {
        return { error: "Invalid course code"};
    }

    // find course in courses database
    const courseIndex = data.course.findIndex(course => course.courseCode === courseCode);
    
    // validate accessCode
    if (courseCode !== accessCode) {
        return { error: "Invalid accessCode for specified course"};
    }
    else {
        // add courseCode to list of courses in user obj
        data.user[userIndex].courses.push(courseCode);
        // add user to list of owners in course obj
        if (courseIndex === -1) {
            const newCourse = {
                courseCode,
                owners: [user.userId]
            }
            data.course.push(newCourse);
        } else {
            data.course[courseIndex].owners.push(user.userId);
        }
        setData(data);
        return {};

    }

}

async function addNewCourse(token, courseCode, accessCode, title, description, termOffering, enrolmentRules) {
    const userToken = tokenValidator(token);

    if ('error' in userToken) {
        return userToken;
    }

    const userID = userToken.tokenUserId;

    let data = getData();

    const user = data.user.find(user => user.userId == userID);
    const userIndex = data.user.findIndex(user => user.userId == userID);
    
    // error checking params
    if (/^[A-Z]{4}\d{4}$/.test(courseCode) === false) {
        return { error: "Invalid course code. Please select a course code of the format:[A-Z]{4}[0-9]{4}!"};
    }
    if (title.length() < 15) {
        return { error: "Title must be at least 15 characters long!"};
    }
    if (description.length() < 30) {
        return { error: "Description must be at least 30 characters long!"};
    }
    // assume frontend sends valid termOffering string e.g. "Summer Term, Term 1, Term 2, Term 3"
    // assume frontend sends valid enrolmentRules string e.g .Prerequisite: COMP1511 or DPST1091 or COMP1917 or COMP1921
    // const termsOffered = termOffering.split(",");
    // const termsOfferedValid = termsOffered.filter(term => ((term === "Term 1") || (term === "Term 2") || (term === "Term 3") || (term === "Summer Term")));

    // check if course already exists
    const res = await fetch(`http://localhost:5005/info/course/${courseCode}`);
    if (res.ok) {
        return { error: "There is already a course with the same code. Please make sure you are not adding a duplicate course or choose a new code!"};
    }
    // how to make it a core course/prescribed elective for a program/spec
    // maybe include fiels for "core", "prescribed_elective", "gen_ed"
    // append courseObj to coursesFormattedRaw.json 
    return {}
}
// this route is used to update the course DB generated by the webscraper, with changes made by admins
function updateCourseDB(token, updatedCourses) {
    // console.log("Iam in updateCourseDB function!");
    // console.log(`This is ${token}`);
    const userToken = tokenValidator(token);

    if ('error' in userToken) {
        return userToken;
    }
    // need to get relative path
    // const coursesDBPath = "/home/sauron4/github-classroom/unsw-cse-comp99-3900/capstone-project-25t2-3900-h18a-date/backend/src/handbook-scraper/data/scrapers/coursesFormattedRaw.json";
    // const coursesDB = JSON.parse(fs.readFileSync(coursesDBPath, 'utf8'));
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);

    const coursesPath = path.join(__dirname, 'handbook-scraper', 'data', 'scrapers', 'coursesFormattedRaw.json');
    const coursesDB = JSON.parse(fs.readFileSync(coursesPath, 'utf8'));
    updatedCourses = JSON.parse(updatedCourses);
    // console.log(`this is updated courses: ${updatedCourses}`);
    // obj["myprop"] = "myprop" value
    // const updatedCoursesMap = new Map(updatedCourses);
    for (const code of Object.keys(updatedCourses)) {
        // console.log(`The current code is ${code}`);
        // for (const [code, changes] of updatedCoursesMap) {
        // check that course exists in DB (sanity check because if admin was able to add it to dashboard, it should already exist in DB)
        if (!coursesDB[code]) {
            // console.log("Could not find code in coursesDB");
            return { error: "Updated course does not exist in hanbook"};
        } else {
            // update description, terms and prerequisite fields of course in DB
            coursesDB[code]["description"] = updatedCourses[code]["description"];
            let newTermString = "";
            for (const term of updatedCourses[code]["terms"]) {
                const termNum = term[1];
                const fullTerm = "Term " + termNum + ", ";
                newTermString += fullTerm
            }
            coursesDB[code]["terms"] = newTermString;
            //update prereqs
            const prereqRules = updatedCourses[code]["prereqRules"];
            // array of AND prereqs
            const andObj = new PrintLogic("and");
            const allOf = prereqRules["allOf"];
            for (const anyOf of allOf) {
                const orObj = new PrintLogic("or");
                for (const constituentPrereq of anyOf["anyOf"]) {
                    orObj.add(new childNode(constituentPrereq["code"]));
                }
                andObj.add(orObj);
            }
            coursesDB[code]["enrolment_rules"] = "Prerequisite: " + andObj.toString() + "<br/><br/>"
        }
    }
    //test changes were applied
    // console.log(coursesDB["COMP1511"]);
    const coursesDBString = JSON.stringify(coursesDB);
    fs.writeFileSync(coursesPath, coursesDBString);
    return {};
}

export {
    getCourseList,
    addCourse,
    updateCourseDB
};